---
- name: my test playbook
  hosts: webservers
  user: vinny
  become: yes
  tasks:
    - name: copying a file
      copy:
        src: /home/vinny/index.html
        dest: /home/vinny
        owner: rocky
