---
- name: my test playbook
  hosts: webservers
  user: vinny
  become: true
  connection: ssh
  tasks:
    - name: creating directory
      file:
        path: /home/vinny/victor
        state: directory
