--- #handlers
- hosts: webservers
  user: vinny
  become: yes
  connection: ssh

  tasks:
    - name: installing HTTPD into hosts
      action: yum name=httpd state=present
      notify: start httpd service



  handlers:
    - name: start httpd service 
      action: service name=httpd state=started
