--- # using variables
- hosts: webservers
  user: vinny
  become: yes
  connection: ssh

  vars:
    pkgname: httpd

  tasks:
    - name: installing package
      action: yum name='{{pkgname}}' state=present
